"""added first_edit

Revision ID: 2cc6dea79f5f
Revises: c4faf26e7f3e
Create Date: 2022-02-14 23:13:16.485881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc6dea79f5f'
down_revision = 'c4faf26e7f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_edit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_edit')
    # ### end Alembic commands ###
