"""empty message

Revision ID: c4faf26e7f3e
Revises: 954149a92857
Create Date: 2022-02-14 22:01:14.758035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4faf26e7f3e'
down_revision = '954149a92857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_login')
    # ### end Alembic commands ###
