"""added ability to set an icon for user and task

Revision ID: ef8e4c5f8c07
Revises: 2cc6dea79f5f
Create Date: 2022-02-24 19:32:22.499413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8e4c5f8c07'
down_revision = '2cc6dea79f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('icon', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('marked_for_complete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('profile_icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_icon')
    op.drop_column('task', 'marked_for_complete')
    op.drop_column('task', 'icon')
    # ### end Alembic commands ###
